week 2
chanelnb/sps-portfolio pull request #4
Opened 2020-02-27 05:06 UTC by chanelnb

portfolio

2020-02-28 00:14 UTC, ackao requested changes
great job with the assignment, just make sure to undo the change to the tutorial file.

2020-02-28 00:14 UTC, ackao commented on walkthroughs/week-1-web-development/portfolio-walkthrough.md
> +```bashteachme ~/software-product-sprint/walkthroughs/week-1-web-development/portfolio-walkthrough.md
you probably didn't intend to modify this walkthrough file

2020-02-28 17:36 UTC, chanelnb commented
It will be fixed thank you

2020-03-01 20:17 UTC, ackao approved these changes

2020-03-01 20:17 UTC, merged